# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.7.2

definitions:
  steps:
  - step: &build-test
      name: Run tests
      caches:
      - pip
      script:
      - python -m pip install --upgrade pip
      - python -m pip install poetry
      - poetry install
      - poetry run black --check
      - poetry run flake8
      - poetry run pydocstyle podcast_log tests --add-ignore D105,D107
      - poetry run mypy
      - poetry run python -m pytest --junitxml=./test-reports/junit.xml --cov-report xml:./test-reports/coverage.xml --cov podcast_log tests
      - poetry run codecov -t $CODECOV_KEY
  - step: &deploy
      name: Deploy to staging
      caches:
      - pip
      deployment: staging
      script:
      - export REPO_URL=http://bitbucket.org/$BITBUCKET_REPO_FULL_NAME
      - python -m pip install --upgrade pip
      - python -m pip install fabric patchwork jinja2 python-dotenv
      - fab -r deploy_tools/fabfile.py -H ubuntu@$HOSTNAME deploy

pipelines:
  branches:
    '*':
    - step: *build-test
    develop:
    - step: *build-test
    - step: *deploy
    master:
    - step: *build-test
    - step: *deploy
    - step:
        <<: *deploy
        name: Deploy to production
        deployment: production
        trigger: manual
