[tool.poetry]
name = "podcast-log"
version = "0.2.1"
description = "Description"
authors = ["Matt Kramer <matthew.robert.kramer@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
feedparser = "^5.2"
flask = "^1.1"
flask-migrate = "^2.5"
flask-sqlalchemy = "^2.4"
flask-table = "^0.5.0"
flask-wtf = "^0.14.2"
gunicorn = "^19.9"
marshmallow = "=3.0.0rc8"
psycopg2-binary = "^2.8"
python-dotenv = "^0.10.3"

[tool.poetry.dev-dependencies]
black = "=19.3b0"
codecov = "^2.0"
fabric = "^2.4"
mypy = "^0.720.0"
patchwork = "^1.0"
pydocstyle = "^4.0"
pytest = "^5.0"
pytest-cov = "^2.7"
pytest-docstyle = "^1.5"
pytest-flake8 = "^1.0"
pytest-mypy = "^0.3.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
