[tool.poetry]
name = "podcast-log"
version = "0.2.1"
description = "A simple Django application for following and keeping a podcast listen log."
license = "MIT"
authors = ["Matt Kramer <matthew.robert.kramer@gmail.com>"]
readme = "README.md"
repository = "https://bitbucket.org/mattkram/podcast-log"
packages = [
    { include = "podcast_log" },
]

[tool.poetry.dependencies]
python = "^3.7"
feedparser = "^5.2"
flask = "^1.0"
flask-wtf = "^0.14.2"
flask-migrate = "^2.3"
flask-sqlalchemy = "^2.3"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0",allows-prereleases = true}
pytest = "^4.2"
pytest-cov = "^2.6"
flask-dotenv = "^0.1.1"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
