# Generated by Django 2.1.5 on 2019-01-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_log', '0010_episode_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='summary',
            field=models.CharField(max_length=500),
        ),
    ]
