# Generated by Django 2.1.5 on 2019-01-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_log', '0011_auto_20190118_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='publication_date',
            new_name='publication_timestamp',
        ),
    ]
