# Generated by Django 2.1.5 on 2019-01-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_log', '0012_auto_20190118_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='status',
            field=models.CharField(choices=[('L', 'Listened'), ('I', 'Ignored'), ('S', 'Skipped'), ('P', 'In Progress'), ('Q', 'Queued')], default='Q', max_length=1),
        ),
    ]
