# Generated by Django 2.1.5 on 2019-01-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_log', '0013_auto_20190118_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
