# Generated by Django 2.1.5 on 2019-01-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_log', '0016_auto_20190122_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio_url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
