# Generated by Django 2.1.5 on 2019-01-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_log', '0017_auto_20190122_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio_url',
            field=models.URLField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
