# Generated by Django 2.1.5 on 2019-01-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_log', '0018_auto_20190122_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
