# Generated by Django 2.1.5 on 2019-01-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_log', '0020_auto_20190125_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_part',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('podcast', 'episode_number', 'episode_part')},
        ),
    ]
