# Generated by Django 2.1.5 on 2019-01-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_log', '0021_auto_20190127_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='summary',
            field=models.CharField(max_length=1000),
        ),
    ]
