# Generated by Django 2.1.5 on 2019-01-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_log', '0022_auto_20190128_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='summary',
            field=models.CharField(max_length=2000),
        ),
    ]
