# Generated by Django 2.1.5 on 2019-01-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_log', '0023_auto_20190129_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
