name: Run Python Tests

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1.3.3
      with:
        version: 1.2.1
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install library and dependencies
      run: poetry install --no-interaction
    - name: Static type checking
      run: |
        poetry run mypy
    - name: Test with pytest
      run: |
        poetry run pytest \
          --junitxml=./test-reports/junit.xml \
          --cov-report xml:./test-reports/coverage.xml \
          --cov podcast_log \
          tests
    - uses: codecov/codecov-action@v2
      with:
        files: ./test-reports/coverage.xml
        env_vars: OS,PYTHON
